services:
  local-db:
    image: mysql:9.0.1
    container_name: Mysql_local
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64
  redis:
    image: redis:latest
    container_name: redis
    ports: 
      - 6379:6379
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./db/redis/data:/data
      - ./db/redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
  music_project_code:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - .env
    container_name: music_project_code
    expose:
     - "3000"
    restart: "always"